### ISSUE TITLE
Broken example on repository README

### ISSUE THREAD

**Issue by blazs** [olivierhagolle/theia_download#2]
When the script is invoked with `-t` parameter, as in this (`python ./theia_download.py -t 'T31TCJ' -c SENTINEL2 -a config_theia.cfg -d 2016-09-01 -f 2016-10-01`) example from the repository, the script breaks because of the single quotation marks `'`. Works fine when the parameter is passed without the quotation marks: `-t T31CJ`.

Best, B.

**Comment by olivierhagolle** [comment]
Thanks, I just corrected the example.
Olivier
