### ISSUE TITLE
'ErrorCode': 403, u'ErrorMessage': u'User profile has not been validated. Please contact an administrator'

### ISSUE THREAD

**Issue by EmilienAlvarez** [olivierhagolle/theia_download#20]
Hi,
I'm trying to download several Sentinel-2 data tiles on an Ubuntu 18.04 system with the following command line :

`python2 ./theia_download.py -t T30UXU -c SENTINEL2 --level LEVEL2A -a config_theia.cfg -d 2017-01-01 -f 2017-09-20 -w /mnt/data/imagery/sentinel-2/download_Theia/new/
`

Some tiles are downloaded properly, then the process stops with the following error message :

> Result is a text file
{u'ErrorCode': 403, u'ErrorMessage': u'User profile has not been validated. Please contact an administrator'}

Any suggestions about this error ?

Thanks,

Emilien Alvarez-Vanhard

**Comment by olivierhagolle** [comment]
Yes, there is a token which expires after some time (2 to 3 hours or so). So if you make a lot of downloads, it is better to split them in different command lines with a reduced number of products. This token was imposed by the security :(
Olivier

**Comment by EmilienAlvarez** [comment]
Ok, i see. Thanks a lot :)

Emilien

**Comment by gillesserco** [comment]
Hello

I have this issue, except that I was never able to download a product, the query is ok.
I did receive the account validation email, and clicked the link.
I am able to enter my profile, and modify it. I also delete and recreate it, with a different password. url: https://sso.theia-land.fr/theia/user/edit.xhtml

I have a colleague here at work that has a 'working' account, he tried my credential and got the same problem as when I tried it myself.
We tried on different unix hosts, different python, different network, always the same error with my account.

At this point we are pretty sure that my account cannot download from theia

As I didn't find a contact (on the web catalogue page), I am using this issue tracker... Sorry to disturb here...

Can you provide an contact where I can get help.

Thanks

Gilles
