### ISSUE TITLE
Several sentinel data on the same date

### ISSUE THREAD

**Issue by jhemmi** [olivierhagolle/theia_download#28]
i've found on "rocket" several zip for sentinel-2A or 2B on the same date
for instance on 30 may 22 for T31TCJ and orbit 51
![image](https://user-images.githubusercontent.com/13019152/176216381-3d9c1217-164e-4869-a87c-bb77ee26a9ec.png)
How to know and choose which is the "good one" ?

**Comment by olivierhagolle** [comment]
Hi,
Both are good ones. You have the upper part in one, and a lower part in the other. This originates from the L1C products from ESA, which does not merge chunks of telemetry.

Olivier
