### ISSUE TITLE
A bug in the script

### ISSUE THREAD

**Issue by blazs** [olivierhagolle/theia_download#3]
When invoking the `theia_download.py` script as shown below I get the following error:

> $ python theia_download.py -t T287PFC -d 2017-05-15 -f 2015-05-15 -c SENTINEL2 -a config_theia.cfg
> tile number much gave this format : T31TFJ
> Traceback (most recent call last):
>   File "theia_download.py", line 103, in <module>
>     if geom=='point':
> NameError: name 'geom' is not defined

**Comment by olivierhagolle** [comment]
As told in the error message, you used a wrong format for the tile number
"T287PFC" has one digit in excess
Best regards,
Olivier
