### ISSUE TITLE
Error when no config file is passed with -a

### ISSUE THREAD

**Issue by vijdz** [olivierhagolle/theia_download#30]
The following is not working 
`./theia_download.py -t T31TDH -d 2019-11-01 -c SENTINEL2 --level LEVEL2A --maxcloud=50 -n`  
Even if the config file is here and with its default name.  

```python
Traceback (most recent call last):
  File "./theia_download.py", line 188, in <module>
    f = open(options.alternative_config)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by jerome-colin** [comment]
Thanks for the bug report, this is fixed
