### ISSUE TITLE
Can't download images

### ISSUE THREAD

**Issue by nicodebo** [olivierhagolle/theia_download#6]
Hello,

I'm trying to download landsat images but I'm getting this message: `authentification is probably wrong`. Also, the `token.json` file is empty. I'm using the following command from the readme:
``` 
python ./theia_download.py -l 'Toulouse' -c Landsat -a config_landsat.cfg -d 2016-09-01 -f 2016-10-01
```

I've also tried to download Sentinel2 images but theia_download return the following message: 
```
Result is a text file
{u'ErrorCode': 403, u'ErrorMessage': u'User profile has not been validated. Please contact an administrator'}
```
The command i'm using is the one from the readme:
```
python ./theia_download.py -l 'Toulouse' -c SENTINEL2 -a config_theia.cfg -d 2016-09-01 -f 2016-10-01
```

I have double checked the credentials in config_theia.cfg and config_landsat.cfg and I'm able to connect on theia websites with those credentials.

**Comment by olivierhagolle** [comment]
Hi,
the script has some issues with special characters in the password, can you change your password using only letters and figures ?
Olivier

**Comment by nicodebo** [comment]
I've replaced special characters in my password and it's working perfectly now.
Thank you very much and have a nice day

**Comment by ayoubkarine** [comment]
Hi,
I have the same problem. And in theia interface, I can't use a password without using letters and uppercase letter.
What I should do ?

**Comment by olivierhagolle** [comment]
Hi Karine, 
That's strange, because I have updated the tool a few months ago to add quotes and avoid the issue.
Moreover, the older version, with lowercase and uppercase letters should be fine.
Oliiver
