### ISSUE TITLE
Cannot download Venus images

### ISSUE THREAD

**Issue by petket-5** [olivierhagolle/theia_download#7]
Hi,

 I am not able to download images of Venus when setting the platform accordingly to `-p VENUS`
When removing the platform, the only results shown are from Sentinel-2, but looking at the website there are clearly some images available from Venus for the given region + period.

The whole command line for this issue is:

`python theia_download.py -a config_theia.cfg -w ../SO2 -p VENUS -d 2018-08-01 -f 2018-09-30 --lat 42.801 --lon 1.2 -n`

Also, I cannot set the site (SO2) directly using a parameter like `TILE` for Sentinel - I always have to set it using the lat/lon parameters.

Thank you in advance!

Kind regards,
Peter

**Comment by olivierhagolle** [comment]
Thanks Peter,
 it's a bug, but you can mitigate it by using -c VENUS, instead of -p VENUS
Olivier
