### ISSUE TITLE
VENUS collection is not "level aware"

### ISSUE THREAD

**Issue by sgascoin** [olivierhagolle/theia_download#8]
By default VENUS collection downloads L2A and L1C and the level option cannot be used

To save bandwidth quickfix Line 219 with

    if options.collection=="SENTINEL2" or options.collection=="VENUS":

and Line 77

    parser.add_option( '--level', type='choice', action='store', dest='level',\
                       choices=['LEVEL1C','LEVEL2A','LEVEL3A'],  help='product level for reflectance products',default='LEVEL2A')

**Comment by olivierhagolle** [comment]
Merci, c'est fait. La prochaine fois, tu peux même faire un pull request ;)
